---
# tasks file for ansible-common-utilities

- block:
    - name: Install htop
      apt:
        name: htop
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

    - name: Install python-software-properties
      apt:
        name: python-software-properties
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes
      when: ansible_distribution_version is version_compare('16.04', '<=')


    - name: Install python3-software-properties
      apt:
        name: python3-software-properties
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes
      when: ansible_distribution_version is version_compare('20.04', '>=')


    - name: Install realpath
      apt:
        name: realpath
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes
      when: ansible_distribution_version is version_compare('16.04', '<=')

    - name: Install tree
      apt:
        name: tree
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

    - name: Install vim
      apt:
        name: vim
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

    - name: Ensure ping is intalled
      apt:
        name: inetutils-ping
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes
    
    - name: ensure host is installed
      apt:
        name: bind9-host
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

    - name: ensure dnsutils is installed
      apt:
        name: dnsutils
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes
    
    - name: ensure traceroute is installed
      apt:
        name: inetutils-traceroute
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

  become: yes
  become_method: sudo
  tags:
  - common
